name: artifact

env: 
  ARTIFACT_NAME : 'artifact'

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.ARTIFACT_NAME }}
          path: .
       
  
# create an environment variable for the artifact name
# create one job w/ two steps
#  actions/checkout & actions/upload-artifact

